### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by michaelzhou0723** [sw-gong/spiralnet_plus#1]
I'm using spiral convolution for one of my project and it works well. So I would like to plug in spiral++ and see how it goes. Will the code be released this weekends?

**Comment by sw-gong** [comment]
I was super busy in the past weeks. Please allow me a few more days to prepare a clean repository. Thank you! :)

**Comment by michaelzhou0723** [comment]
Could you roughly estimate a date when you will get time to push the code?

**Comment by sw-gong** [comment]
Hi @michaelzhou0723 ,

The code has already been released.
