### ISSUE TITLE
How to incorporate auxiliary input information 

### ISSUE THREAD

**Issue by asadabbas09** [sw-gong/spiralnet_plus#3]
Thanks for awesome work.

I'm trying to use SpiralNet++ for CFD analysis (something like this [paper](https://arxiv.org/abs/1810.08217) but for 3D) and getting good results.

I would like to know what's the best way to incorporate auxiliary information (other than input coordinates and spiral sequences) in the network.

For example, I would like to introduce input freestream velocity (x,y, z-direction) and angle of attack (scaler value) to the network.

Many Thanks.

**Comment by sw-gong** [comment]
Hi @asadabbas09 

Thanks for your interest in SpiralNet++. You can simply concatenate auxiliary features with input coordinates. Note that spiral sequences generation is independent with node features.

**Comment by asadabbas09** [comment]
If I understand correctly, In the case where I have only one single scaler value (e.g. angle of attack = 30) as extra auxiliary input information, then I would concatenate 30 with all input coordinates (x,y,z, 30) making input coordinates 4 dimensional?

**Comment by sw-gong** [comment]
Yes, you can give it a try and feature normalization may help.

**Comment by asadabbas09** [comment]
Thanks @sw-gong .

Just a quick question, if I have mesh objects each having a different number of nodes (vertices) or faces would training and spiral conv still work?
