### ISSUE TITLE
Shape Correspondece 

### ISSUE THREAD

**Issue by didiya5154** [sw-gong/spiralnet_plus#7]
Hi, thank you for your work.
I have tried your code about shape correspondence on FAUST and the results are close with that in your paper. However, I noticed that you did not shuffle the vertex orders, so I want to know why we need a GCN to learn correspondence since the vertices of meshes in FAUST are already in one-to-one correspondence.
And I have tried to shuffle the vertex orders then Spiralnet++ did not work. So I am confused and want to ask for your advice. Thanks a lot.

**Comment by sw-gong** [comment]
The correspondence task with SpiralNet++ is to demonstrate the _**efficiency**_ and _**effectiveness**_ of **this simple idea** which enforces the consistency of model training by serializing local vertices in a certain order so as to learn a functional mapping from meshes (with spatial coordinates) to classes with the provision of a template mesh (Remark: the performance of most of the graph/mesh convolution methods on the shelf evaluated on the well-known registered shape correspondence datasets will see deterioration to some degree unless **_a correspondence estimation method is truly tessellation-oblivious_**.). This is obviously not universally applicable toward _**open-world shape correspondence problems**_, where some further issues, for instance, in the perspective of graph matching or the embeddings of manifolds with the goal of ensuring training consistency, are required to resolve to replicate and match the performance as shown in the correspondence experiment.

Note that a registered template is normally accessible for shape reconstruction and classification as the experiments that are shown in the paper, which are ideal scenarios to apply SpiralNet++.
